/**
 * Varisai and alankara notation as published by karnATik (Royal Carpet), the
 * long-standing free Carnatic archive, whose beginner lessons are the version
 * most widely reproduced elsewhere — Shivkumar Kalyanaraman's archive cites
 * this same source for its own basics pages.
 *
 * The strings below are the source notation VERBATIM, one string per avartana,
 * so that any line in this app can be checked against the published lesson
 * without decoding our own format first. `parseKarnatikLine` turns them into
 * the app's NotationElement form.
 *
 * Notation conventions used by the source:
 *   lowercase s r g m p d n  a swara in the madhya sthayi
 *   uppercase S N D ...      the same swara one octave up (tara sthayi)
 *   ,                        a karvai: hold the previous swara one more akshara
 *   -                        a cell separator; it occupies no time
 *   |  ||                    anga and avartana boundaries; the tala supplies these
 *
 * Sources:
 *   https://www.karnatik.com/lesson1.shtml  sarali varisai
 *   https://www.karnatik.com/lesson2.shtml  janta varisai
 *   https://www.karnatik.com/lesson3.shtml  dhatu varisai
 *   https://www.karnatik.com/lesson4.shtml  melsthayi varisai
 *   https://www.karnatik.com/lesson5.shtml  keezhsthayi varisai
 *   https://www.karnatik.com/lesson6.shtml  alankaras in the sapta talas
 *
 * All exercises are in Mayamalavagowla. The varisai lessons are in Adi tala;
 * each alankara carries its own tala.
 */

export const KARNATIK_SOURCE = {
  name: 'karnATik (Royal Carpet) beginner lessons',
  url: 'https://www.karnatik.com/beginner.shtml',
} as const

/** Sarali varisai 1–14, one array of avartana lines each. */
export const SARALI_SOURCE: readonly (readonly string[])[] = [
  [
    "s r g m | p d | n S ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r - s r - | s r | g m ||",
    "s r g m | p d | n S ||",
    "S n - S n - | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g - s | r g - | s r ||",
    "s r g m | p d | n S ||",
    "S n d - s | n d - | s n ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m - | s r | g m - ||",
    "s r g m | p d | n s ||",
    "S n d p - | S n | d p - ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p , - | s r ||",
    "s r g m | p d | n S ||",
    "S n d p | m , - | S n ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p d - | s r ||",
    "s r g m | p d | n S ||",
    "S n d p | m g - | S n ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p d | n , ||",
    "s r g m | p d | n S ||",
    "S n d p | m g | r , ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p m | g r ||",
    "s r g m | p d | n S ||",
    "S n d p | m p | d n ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p m | d p ||",
    "s r g m | p d | n S ||",
    "S n d p | m p | g m ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p , | g m ||",
    "p , , , | p , | , , ||",
    "g m p d | n d | p m ||",
    "g m p - g | m g | r s ||",
  ],
  [
    "S , n d | n , | d p ||",
    "d , p m | p , | p , ||",
    "g m p d | n d | p m ||",
    "g m p - g | m g | r s ||",
  ],
  [
    "S S n d | n n | d p ||",
    "d d p m | p , | p , ||",
    "g m p d | n d | p m ||",
    "g m p - g | m g | r s ||",
  ],
  [
    "s r g r | g , - | g m ||",
    "p m p , - | d p | d , ||",
    "m p d p | d n | d p ||",
    "m p d p | m g | r s ||",
  ],
  [
    "s r g m | p , | p , ||",
    "d d p , | m m | p , ||",
    "d n S , | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
]

/** Janta varisai. */
export const JANTA_SOURCE: readonly (readonly string[])[] = [
  [
    "s s r r | g g | m m ||",
    "p p d d | n n | S S ||",
    "S S n n | d d | p p ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s r r | g g | m m ||",
    "r r g g | m m | p p ||",
    "g g m m | p p | d d ||",
    "m m p p | d d | n n ||",
    "p p d d | n n | S S ||",
    "S S n n | d d | p p ||",
    "n n d d | p p | m m ||",
    "d d p p | m m | g g ||",
    "p p m m | g g | r r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s r r | g g | r r ||",
    "s s r r | g g | m m ||",
    "r r g g | m m | g g ||",
    "r r g g | m m | p p ||",
    "g g m m | p p | m m ||",
    "g g m m | p p | d d ||",
    "m m p p | d d | p p ||",
    "m m p p | d d | n n ||",
    "p p d d | n n | d d ||",
    "p p d d | n n | S S ||",
    "S S n n | d d | n n ||",
    "S S n n | d d | p p ||",
    "n n d d | p p | d d ||",
    "n n d d | p p | m m ||",
    "d d p p | m m | p p ||",
    "d d p p | m m | g g ||",
    "p p m m | g g | m m ||",
    "p p m m | g g | r r ||",
    "m m g g | r r | g g ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s r - s | s r | s r ||",
    "s s r r | g g | m m ||",
    "r r g - r | r g | r g ||",
    "r r g g | m m | p p ||",
    "g g m - g | g m | g m ||",
    "g g m m | p p | d d ||",
    "m m p - m | m p | m p ||",
    "m m p p | d d | n n ||",
    "p p d - p | p d | p d ||",
    "p p d d | n n | S S ||",
    "S S n - S | S n | S n ||",
    "S S n n | d d | p p ||",
    "n n d - n | n d | n d ||",
    "n n d d | p p | m m ||",
    "d d p - d | d p | d p ||",
    "d d p p | m m | g g ||",
    "p p m - p | p m | p m ||",
    "p p m m | g g | r r ||",
    "m m g - m | m g | m g ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s r r | g - s | r g ||",
    "s s r r | g g | m m ||",
    "r r g g | m - r | g m ||",
    "r r g g | m m | p p ||",
    "g g m m | p - g | m p ||",
    "g g m m | p p | d d ||",
    "m m p p | d - m | p d ||",
    "m m p p | d d | n n ||",
    "p p d d | n - p | d n ||",
    "p p d d | n n | S S ||",
    "S S n n | d - S | n d ||",
    "S S n n | d d | p p ||",
    "n n d d | p - n | d p ||",
    "n n d d | p p | m m ||",
    "d d p p | m - d | p m ||",
    "d d p p | m m | g g ||",
    "p p m m | g - p | m g ||",
    "p p m m | g g | r r ||",
    "m m g g | r - m | g r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s , r | r , | g g ||",
    "s s r r | g g | m m ||",
    "r r , g | g , | m m ||",
    "r r g g | m m | p p ||",
    "g g , m | m , | p p ||",
    "g g m m | p p | d d ||",
    "m m , p | p , | d d ||",
    "m m p p | d d | n n ||",
    "p p , d | d , | n n ||",
    "p p d d | n n | S S ||",
    "S S , n | n , | d d ||",
    "S S n n | d d | p p ||",
    "n n , d | d , | p p ||",
    "n n d d | p p | m m ||",
    "d d , p | p , | m m ||",
    "d d p p | m m | g g ||",
    "p p , m | m , | g g ||",
    "p p m m | g g | r r ||",
    "m m , g | g , | r r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s , s r | , r | g g ||",
    "s s r r | g g | m m ||",
    "r , r g | , g | m m ||",
    "r r g g | m m | p p ||",
    "g , g m | , m | p p ||",
    "g g m m | p p | d d ||",
    "m , m p | , p | d d ||",
    "m m p p | d d | n n ||",
    "p , p d | , d | n n ||",
    "p p d d | n n | S S ||",
    "S , S n | , n | d d ||",
    "S S n n | d d | p p ||",
    "n , n d | , d | p p ||",
    "n n d d | p p | m m ||",
    "d , d p | , p | m m ||",
    "d d p p | m m | g g ||",
    "p , p m | , m | g g ||",
    "p p m m | g g | r r ||",
    "m , m g | , g | r r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s s r | r r | g g ||",
    "s s r r | g g | m m ||",
    "r r r g | g g | m m ||",
    "r r g g | m m | p p ||",
    "g g g m | m m | p p ||",
    "g g m m | p p | d d ||",
    "m m m p | p p | d d ||",
    "m m p p | d d | n n ||",
    "p p p d | d d | n n ||",
    "p p d d | n n | S S ||",
    "S S S n | n n | d d ||",
    "S S n n | d d | p p ||",
    "n n n d | d d | p p ||",
    "n n d d | p p | m m ||",
    "d d d p | p p | m m ||",
    "d d p p | m m | g g ||",
    "p p p m | m m | g g ||",
    "p p m m | g g | r r ||",
    "m m m g | g g | r r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s , r g | , - s | r g ||",
    "s s r r | g g | m m ||",
    "r , g m | , - r | g m ||",
    "r r g g | m m | p p ||",
    "g , m p | , - g | m p ||",
    "g g m m | p p | d d ||",
    "m , p d | , - m | p d ||",
    "m m p p | d d | n n ||",
    "p , d n | , - p | d n ||",
    "p p d d | n n | S S ||",
    "S , n d | , - S | n d ||",
    "S S n n | d d | p p ||",
    "n , d p | , - n | d p ||",
    "n n d d | p p | m m ||",
    "d , p m | , - d | p m ||",
    "d d p p | m m | g g ||",
    "p , m g | , - p | m g ||",
    "p p m m | g g | r r ||",
    "m , g r | , - m | g r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s r , g | , - s | r g ||",
    "s s r r | g g | m m ||",
    "r g , m | , - r | g m ||",
    "r r g g | m m | p p ||",
    "g m , p | , - g | m p ||",
    "g g m m | p p | d d ||",
    "m p , d | , - m | p d ||",
    "m m p p | d d | n n ||",
    "p d , n | , - p | d n ||",
    "p p d d | n n | S S ||",
    "S n , d | , - S | n d ||",
    "S S n n | d d | p p ||",
    "n d , p | , - n | d p ||",
    "n n d d | p p | m m ||",
    "d p , m | , - d | p m ||",
    "d d p p | m m | g g ||",
    "p m , g | , - p | m g ||",
    "p p m m | g g | r r ||",
    "m g , r | , - m | g r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s , r , | g - s | r g ||",
    "s s r r | g g | m m ||",
    "r , g , | m - r | g m ||",
    "r r g g | m m | p p ||",
    "g , m , | p - g | m p ||",
    "g g m m | p p | d d ||",
    "m , p , | d - m | p d ||",
    "m m p p | d d | n n ||",
    "p , d , | n - p | d n ||",
    "p p d d | n n | S S ||",
    "S , n , | d - S | n d ||",
    "S S n n | d d | p p ||",
    "n , d , | p - n | d p ||",
    "n n d d | p p | m m ||",
    "d , p , | m - d | p m ||",
    "d d p p | m m | g g ||",
    "p , m , | g - p | m g ||",
    "p p m m | g g | r r ||",
    "m , g , | r - m | g r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s s m m | g g | r r ||",
    "s s r r | g g | m m ||",
    "r r p p | m m | g g ||",
    "r r g g | m m | p p ||",
    "g g d d | p p | m m ||",
    "g g m m | p p | d d ||",
    "m m n n | d d | p p ||",
    "m m p p | d d | n n ||",
    "p p S S | n n | d d ||",
    "p p d d | n n | S S ||",
    "S S p p | d d | n n ||",
    "S S n n | d d | p p ||",
    "n n m m | p p | d d ||",
    "n n d d | p p | m m ||",
    "d d g g | m m | p p ||",
    "d d p p | m m | g g ||",
    "p p r r | g g | m m ||",
    "p p m m | g g | r r ||",
    "m m s s | r r | g g ||",
    "m m g g | r r | s s ||",
  ],
]

/** Dhatu (daatu) varisai — the leaping patterns. */
export const DHATU_SOURCE: readonly (readonly string[])[] = [
  [
    "s s m m | r r | g g ||",
    "s s r r | g g | m m ||",
    "r r p p | g g | m m ||",
    "r r g g | m m | p p ||",
    "g g d d | m m | p p ||",
    "g g m m | p p | d d ||",
    "m m n n | p p | d d ||",
    "m m p p | d d | n n ||",
    "p p S S | d d | n n ||",
    "p p d d | n n | S S ||",
    "S S p p | n n | d d ||",
    "S S n n | d d | p p ||",
    "n n m m | d d | p p ||",
    "n n d d | p p | m m ||",
    "d d g g | p p | m m ||",
    "d d p p | m m | g g ||",
    "p p r r | m m | g g ||",
    "p p m m | g g | r r ||",
    "m m s s | g g | r r ||",
    "m m g g | r r | s s ||",
  ],
  [
    "s m g m | r g | s r ||",
    "s g r g | s r | g m ||",
    "r p m p | g m | r g ||",
    "r m g m | r g | m p ||",
    "g d p d | m p | g m ||",
    "g p m p | g m | p d ||",
    "m n d n | p d | m p ||",
    "m d p d | m p | d n ||",
    "p S n S | d n | p d ||",
    "p n d n | p d | n S ||",
    "S p d p | n d | S n ||",
    "S d n d | S n | d p ||",
    "n m p m | d p | n d ||",
    "n p d p | n d | p m ||",
    "d g m g | p m | d p ||",
    "d m p m | d p | m g ||",
    "p r g r | m g | p m ||",
    "p g m g | p m | g r ||",
    "m s r s | g r | m g ||",
    "m r g r | m g | r s ||",
  ],
  [
    "s r s g | r g | r m ||",
    "s m g r | s r | g m ||",
    "r g r m | g m | g p ||",
    "r p m g | r g | m p ||",
    "g m g p | m p | m d ||",
    "g d p m | g m | p d ||",
    "m p m d | p d | p n ||",
    "m n d p | m p | d n ||",
    "p d p n | d n | d S ||",
    "p S n d | p d | n S ||",
    "S n S d | n d | n p ||",
    "S p d n | S n | d p ||",
    "n d n p | d p | d m ||",
    "n m p d | n d | p m ||",
    "d p d m | p m | p g ||",
    "d g m p | d p | m g ||",
    "p m p g | m g | m r ||",
    "p r g m | p m | g r ||",
    "m g m r | g r | g s ||",
    "m s r g | m g | r s ||",
  ],
]

/** Melsthayi varisai — reaching into the octave above. */
export const MELSTHAYI_SOURCE: readonly (readonly string[])[] = [
  [
    "s r g m | p d | n S ||",
    "S , , , | S , | , , ||",
    "d n S R | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p d | n S ||",
    "S , , , | S , | , , ||",
    "d n S R | S S | R S ||",
    "S R - S n | d p | m p ||",
    "d n S R | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p d | n S ||",
    "S , , , | S , | , , ||",
    "d n S R | G R | S R ||",
    "S R - S n | d p | m p ||",
    "d n S R | S S | R S ||",
    "S R - S n | d p | m p ||",
    "d n S R | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p d | n S ||",
    "S , , , | S , | , , ||",
    "d n S R | G M | G R ||",
    "S R - S n | d p | m p ||",
    "d n S R | G R | S R ||",
    "S R - S n | d p | m p ||",
    "d n S R | S S | R S ||",
    "S R - S n | d p | m p ||",
    "d n S R | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
  [
    "s r g m | p d | n S ||",
    "S , , , | S , | , , ||",
    "d n S R | G M | P M ||",
    "G R - S n | d p | m p ||",
    "d n S R | G M | G R ||",
    "S R - S n | d p | m p ||",
    "d n S R | G R | S R ||",
    "S R - S n | d p | m p ||",
    "d n S R | S S | R S ||",
    "S R - S n | d p | m p ||",
    "d n S R | S n | d p ||",
    "S n d p | m g | r s ||",
  ],
]

/** Keezhsthayi varisai — reaching into the octave below. */
export const KEEZHSTHAYI_SOURCE: readonly (readonly string[])[] = [
  [
    "S n d p | m g | r s ||",
    "s , , , | s , | , , ||",
    "g r s n. | s r | g m ||",
    "s r g m | p d | n S ||",
  ],
  [
    "S n d p | m g | r s ||",
    "s , , , | s , | , , ||",
    "g r s n. | s s | n. s ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s r | g m ||",
    "s r g m | p d | n S ||",
  ],
  [
    "S n d p | m g | r s ||",
    "s , , , | s , | , , ||",
    "g r s n. | d. n. | s n. ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s s | n. s ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s r | g m ||",
    "s r g m | p d | n S ||",
  ],
  [
    "S n d p | m g | r s ||",
    "s , , , | s , | , , ||",
    "g r s n. | d. p. | d n. ||",
    "s n. s r | g m | p m ||",
    "g r s n. | d. n. | s n. ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s s | n. s ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s r | g m ||",
    "s r g m | p d | n S ||",
  ],
  [
    "S n d p | m g | r s ||",
    "s , , , | s , | , , ||",
    "g r s n. | d. p. | m. p. ||",
    "d n. s r | g m | p m ||",
    "g r s n. | d. p. | d n. ||",
    "s n. s r | g m | p m ||",
    "g r s n. | d. n. | s n. ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s s | n. s ||",
    "s n. s r | g m | p m ||",
    "g r s n. | s r | g m ||",
    "s r g m | p d | n S ||",
  ],
]

export interface AlankaraSource {
  talaId: string
  name: string
  aksharaCount: number
  lines: readonly string[]
}

/** One alankara per suladi sapta tala, in the order the source prints them. */
export const ALANKARA_SOURCE: readonly AlankaraSource[] = [
  { talaId: "dhruva", name: "Dhruva", aksharaCount: 14, lines: [
    "s r g m | g r | s r g r | s r g m ||",
    "r g m p | m g | r g m g | r g m p ||",
    "g m p d | p m | g m p m | g m p d ||",
    "m p d n | d p | m p d p | m p d n ||",
    "p d n S | n d | p d n d | p d n S ||",
    "S n d p | d n | S n d n | S n d p ||",
    "n d p m | p d | n d p d | n d p m ||",
    "d p m g | m p | d p m p | d p m g ||",
    "p m g r | g m | p m g m | p m g r ||",
    "m g r s | r g | m g r g | m g r s ||",
  ] },
  { talaId: "matya", name: "Matya", aksharaCount: 10, lines: [
    "s r g r | s r | s r g m ||",
    "r g m g | r g | r g m p ||",
    "g m p m | g m | g m p d ||",
    "m p d p | m p | m p d n ||",
    "p d n d | p d | p d n S ||",
    "S n d n | S n | S n d p ||",
    "n d p d | n d | n d p m ||",
    "d p m p | d p | d p m g ||",
    "p m g m | p m | p m g r ||",
    "m g r g | m g | m g r s ||",
  ] },
  { talaId: "rupaka", name: "Rupaka", aksharaCount: 6, lines: [
    "s r | s r g m ||",
    "r g | r g m p ||",
    "g m | g m p d ||",
    "m p | m p d n ||",
    "p d | p d n S ||",
    "S n | S n d p ||",
    "n d | n d p m ||",
    "d p | d p m g ||",
    "p m | p m g r ||",
    "m g | m g r s ||",
  ] },
  { talaId: "jhampa", name: "Jhampa", aksharaCount: 10, lines: [
    "s r g s r s r | g | m , ||",
    "r g m r g r g | m | p , ||",
    "g m p g m g m | p | d , ||",
    "m p d m p m p | d | n , ||",
    "p d n p d p d | n | S , ||",
    "S n d S n S n | d | p , ||",
    "n d p n d n d | p | m , ||",
    "d p m d p d p | m | g , ||",
    "p m g p m p m | g | r , ||",
    "m g r m g m g | r | s , ||",
  ] },
  { talaId: "triputa", name: "Triputa", aksharaCount: 7, lines: [
    "s r g | s r | g m ||",
    "r g m | r g | m p ||",
    "g m p | g m | p d ||",
    "m p d | m p | d n ||",
    "p d n | p d | n S ||",
    "S n d | S n | d p ||",
    "n d p | n d | p m ||",
    "d p m | d p | m g ||",
    "p m g | p m | g r ||",
    "m g r | m g | r s ||",
  ] },
  { talaId: "ata", name: "Ata", aksharaCount: 14, lines: [
    "s r , g , | s , r g , | m , | m , ||",
    "r g , m , | r , g m , | p , | p , ||",
    "g m , p , | g , m p , | d , | d , ||",
    "m p , d , | m , p d , | n , | n , ||",
    "p d , n , | p , d n , | S , | S , ||",
    "S n , d , | S , n d , | p , | p , ||",
    "n d , p , | n , d p , | m , | m , ||",
    "d p , m , | d , p m , | g , | g , ||",
    "p m , g , | p , m g , | r , | r , ||",
    "m g , r , | m , g r , | s , | s , ||",
  ] },
  { talaId: "eka", name: "Eka", aksharaCount: 4, lines: [
    "s r g m ||",
    "r g m p ||",
    "g m p d ||",
    "m p d n ||",
    "p d n S ||",
    "S n d p ||",
    "n d p m ||",
    "d p m g ||",
    "p m g r ||",
    "m g r s ||",
  ] },
]
